apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
spec:
  containers:
  - name: mypod
    image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
    - name: laravel-www
      mountPath: /opt 
  volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: my-azurefile
      - name: laravel-www
        persistentVolumeClaim:
          claimName: laravel-www 
