apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-nfs
  resources:
    requests:
      storage: 100Gi

