apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: myclusterregistry.azurecr.io/phpmyadmin:5.0.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            
        env:
        - name: PMA_HOST
          value: mysql-svc
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD	
          value: "root"       

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: phpmyadmin
